# Generated by Django 3.2.7 on 2021-11-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bioterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bioterio', models.CharField(max_length=100, verbose_name='Bioterio')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('numero', models.CharField(max_length=100, verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Municipio')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
            ],
        ),
        migrations.RemoveField(
            model_name='protocolo',
            name='bioterio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='protocolo',
            name='titulo_protocolo',
            field=models.CharField(max_length=100, null=True, verbose_name='Titulo'),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='user',
            name='idade',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='universidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
