# Generated by Django 3.2.7 on 2021-11-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0004_auto_20211110_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_avaliador',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='É Avaliador ?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_presidente',
            field=models.BooleanField(blank=True, default=False, verbose_name='É presidente ?'),
        ),
    ]
