# Generated by Django 3.2.7 on 2021-11-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0005_auto_20211110_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='status',
            field=models.CharField(blank=True, choices=[('AP', 'APROVADO'), ('RE', 'REPROVADO'), ('PE', 'PENDENTE')], default='PE', max_length=2),
        ),
    ]
