# Generated by Django 3.2.7 on 2021-11-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0007_user_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome: '),
        ),
    ]
