# Generated by Django 3.2.7 on 2021-12-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0008_alter_protocolo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_presidente',
            field=models.BooleanField(default=False, verbose_name='É presidente ?'),
        ),
    ]
