# Generated by Django 3.2.7 on 2021-12-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0009_alter_user_is_presidente'),
        ('Pesquisador', '0009_auto_20211207_2247'),
    ]

    operations = [
    ]
