# Generated by Django 3.2.7 on 2021-12-08 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0010_merge_20211208_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_parecer', models.CharField(max_length=300, verbose_name='Descrição: ')),
                ('recomendado', models.CharField(blank=True, choices=[('Não-recomendado', 'Não Recomendado'), ('Recomendado', 'Recomendado')], default='Assinado', max_length=15)),
                ('protocoloEM', models.ForeignKey(limit_choices_to={'status': 'APROVADO'}, on_delete=django.db.models.deletion.CASCADE, to='Pesquisador.protocolo', verbose_name='Escolha o Protocolo')),
            ],
        ),
    ]
