# Generated by Django 3.2.7 on 2021-12-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0011_parecer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parecer',
            old_name='protocoloEM',
            new_name='protocoloParecer',
        ),
        migrations.AlterField(
            model_name='parecer',
            name='recomendado',
            field=models.CharField(blank=True, choices=[('Não-recomendado', 'Não Recomendado'), ('Recomendado', 'Recomendado')], default='Recomendado', max_length=15),
        ),
    ]
