# Generated by Django 3.2.7 on 2021-12-08 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0012_auto_20211208_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parecer',
            name='desc_parecer',
            field=models.TextField(verbose_name='Descrição: '),
        ),
        migrations.AlterField(
            model_name='parecer',
            name='protocoloParecer',
            field=models.ForeignKey(limit_choices_to={'status': 'PENDENTE'}, on_delete=django.db.models.deletion.CASCADE, to='Pesquisador.protocolo', verbose_name='Escolha o Protocolo'),
        ),
    ]
