# Generated by Django 3.2.7 on 2021-10-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.CharField(max_length=100, verbose_name='Justificativa')),
                ('resumo', models.TextField(verbose_name='Resumo em Português')),
                ('resumo_en', models.TextField(verbose_name='Resumo em Inglês')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_termino', models.DateField(verbose_name='Data de Termino')),
                ('especie', models.CharField(max_length=50, verbose_name='Espécie')),
                ('quantidade', models.IntegerField()),
                ('bioterio', models.CharField(max_length=50, verbose_name='Biotério')),
            ],
        ),
    ]
