# Generated by Django 3.2.7 on 2021-10-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='status',
            field=models.CharField(choices=[('AP', 'APROVADO'), ('RE', 'REPROVADO'), ('PE', 'PENDENTE')], default='PE', max_length=2),
        ),
    ]
