# Generated by Django 3.2.7 on 2021-11-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_protocolo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bioterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bioterio', models.CharField(max_length=100, verbose_name='Bioterio')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('numero', models.CharField(max_length=100, verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Municipio')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
            ],
        ),
        migrations.RemoveField(
            model_name='protocolo',
            name='bioterio',
        ),
        migrations.AddField(
            model_name='protocolo',
            name='titulo_protocolo',
            field=models.CharField(max_length=100, null=True, verbose_name='Titulo'),
        ),
    ]
