# Generated by Django 3.2.7 on 2021-11-28 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pesquisador', '0006_alter_protocolo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encaminhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserProtocolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('protocoloEN', models.ManyToManyField(to='Pesquisador.Protocolo')),
            ],
        ),
    ]
