# Generated by Django 3.2.7 on 2021-12-01 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pesquisador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encaminhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserProtocolo', models.ForeignKey(limit_choices_to={'groups': 3}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Selecione o Avaliador:')),
                ('protocoloEN', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pesquisador.protocolo', verbose_name='Escolha o Protocolo')),
            ],
        ),
    ]
