# Generated by Django 3.2.7 on 2021-12-06 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0008_alter_protocolo_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secretaria', '0002_auto_20211206_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncaminharAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserProtocolo', models.ForeignKey(limit_choices_to={'groups': 4}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Selecione o Presidente:')),
                ('protocoloEN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pesquisador.protocolo', verbose_name='Escolha o Protocolo')),
            ],
        ),
    ]
