# Generated by Django 3.2.7 on 2021-12-06 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0008_alter_protocolo_status'),
        ('secretaria', '0004_auto_20211206_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaminharap',
            name='protocoloEN',
            field=models.ForeignKey(limit_choices_to={'status': 'APROVADO'}, on_delete=django.db.models.deletion.CASCADE, to='Pesquisador.protocolo', verbose_name='Escolha o Protocolo'),
        ),
    ]
